import type { OccupancyViewTableSectionProps } from '../OccupancyViewTableSection';

import { buildOccupancyTableSectionProps } from '../occupancyTableSectionPropsBuilders';

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- сборка пропсов таблицы: много полей из разных хуков
export function buildOccupancyViewModelTableSectionProps(input: Record<string, any>): OccupancyViewTableSectionProps {
  const layout = input.layout;
  return buildOccupancyTableSectionProps({
    bodyCore: {
      assigneeIdToTaskPositions: input.assigneeIdToTaskPositions,
      availabilityDevelopersWithSegments: input.availabilityDevelopersWithSegments,
      cellsPerDay: layout.cellsPerDayCount,
      collapsedParents: input.collapsedParents,
      contextMenuBlurOtherCards: input.contextMenuBlurOtherCards,
      contextMenuTaskId: input.contextMenuTaskId,
      dayColumnWidth: input.dayColumnWidth,
      developerMap: input.developerMap,
      displayAsWeeks: layout.displayAsWeeks,
      displayColumnCount: input.displayColumnCount,
      factChangelogs: input.taskChangelogsRaw ?? new Map(),
      factComments: input.taskComments ?? new Map(),
      factDurations: input.taskChangelogs ?? new Map(),
      factVisible: layout.effectiveFactVisible,
      gitlabFactByLink: input.gitlabFactByLink ?? {},
      getRowId: input.dragAndDrop.getRowId,
      globalNameFilter: input.globalNameFilter,
      goalStoryEpicNames: input.goalStoryEpicNames,
      handleEmptyCellClick: input.handleEmptyCellClick,
      handlePositionPreview: input.handlePositionPreview,
      headerHeight: input.headerHeight,
      holidayDayIndices: input.holidayDayIndices,
      hoverConnectedPhaseIds: input.hoverConnectedForDim,
      hoveredPhaseTaskId: input.hoveredPhaseTaskId,
      isReorderMode: input.isReorderMode,
      legacyCompactLayout: layout.legacyCompactLayout,
      linkingFromTaskId: input.linking.linkingFromTaskId,
      occupancyErrorReasons: input.occupancyData.occupancyErrorReasons,
      occupancyErrorTaskIds: input.occupancyData.occupancyErrorTaskIds,
      overlappingTaskIds: input.overlappingTaskIds,
      parentStatuses: input.parentStatuses,
      parentTypes: input.parentTypes,
      positionPreviews: input.positionPreviews,
      quarterlyPhaseStyle: layout.quarterlyPhaseStyle,
      quarterlySplitTaskColumns: layout.quarterlySplitTaskColumns,
      showIssueCommentsInWeeks: input.showIssueCommentsInWeeks,
      sprintInfos: input.sprintInfos,
      timelineTotalParts: input.timelineTotalParts,
      weekColumns: input.weekColumns,
      rowFieldsVisibility: layout.rowFieldsVisibility,
      segmentEditTaskId: input.segmentEditTaskId,
      setHoveredPhaseTaskId: input.setHoveredPhaseTaskId,
      setTaskRowRef: input.setTaskRowRef,
      sortableRowIds: input.dragAndDrop.sortableRowIds,
      sourceRowEndCell: input.sourceRowEndCell,
      sourceRowPhaseIds: input.sourceRowPhaseIds,
      sprintStartDate: input.effectiveSprintStartDate,
      taskColumnWidth: input.scroll.taskColumnWidth,
      taskLinks: input.taskLinks,
      taskPositions: input.taskPositions,
      taskRowHeights: input.taskRowHeights,
      timelineSettings: input.timelineSettings,
      toggleParent: input.toggleParent,
      totalParts: input.totalParts,
      visibleRows: input.occupancyData.visibleRows,
      workingDays: input.workingDays,
      onCancelLinking: input.onCancelLinking,
      onCompleteLink: input.onCompleteLink,
      onContextMenu: input.occupancyCallbacks.onContextMenu,
      onCreateTaskForParent: input.occupancyCallbacks.onCreateTaskForParent,
      onPositionSave: input.occupancyCallbacks.onPositionSave,
      onSegmentEditCancel: input.onSegmentEditCancel,
      onSegmentEditSave: input.occupancyCallbacks.onSegmentEditSave,
      onStartLinking: input.onStartLinking,
      onTaskClick: input.occupancyCallbacks.onTaskClick,
      onTaskOrderChange: input.occupancyCallbacks.onTaskOrderChange,
    },
    dayColumnWidth: input.dayColumnWidth,
    displayColumnCount: input.displayColumnCount,
    handleTableClickCapture: input.handleTableClickCapture,
    headerCore: {
      allExpanded: input.allExpanded,
      dayColumnWidth: input.dayColumnWidth,
      displayAsWeeks: layout.displayAsWeeks,
      displayColumnCount: input.displayColumnCount,
      errorDayDetails: input.occupancyData.occupancyErrorDetailsByDay,
      errorDayIndices: input.occupancyData.occupancyErrorDays,
      holidayDayIndices: input.holidayDayIndices,
      isReorderMode: input.isReorderMode,
      isResizing: input.isResizing,
      parentIds: input.parentIds,
      setIsReorderMode: input.setIsReorderMode,
      setIsResizing: input.setIsResizing,
      sprintInfos: input.sprintInfos,
      sprintStartDate: input.effectiveSprintStartDate,
      sprintWorkingDaysCount: input.workingDays,
      taskColumnWidth: input.scroll.taskColumnWidth,
      tasks: input.tasks,
      totalStoryPoints: input.totalStoryPoints,
      totalTestPoints: input.totalTestPoints,
      quarterlySplitTaskColumns: layout.quarterlySplitTaskColumns,
      quarterlyWeekTimelineHeader: input.quarterlyWeekTimelineHeader,
      twoLineDayHeader: layout.twoLineDayHeader,
      onCollapseAll: input.collapseAll,
      onExpandAll: input.expandAll,
      onHoveredErrorTaskIdChange: input.setHoveredErrorTaskId,
      onTaskOrderChange: input.occupancyCallbacks.onTaskOrderChange,
    },
    quarterlyPhaseStyle: layout.quarterlyPhaseStyle,
    showLinks: layout.showLinks,
    tableScrollRef: input.scroll.tableScrollRef,
    tableWidth: input.timelineDimensions.tableWidth,
    taskArrows: {
      devToQaTaskId: input.devToQaTaskId,
      hoveredPhaseTaskId: input.hoveredPhaseTaskId,
      linkingFromTaskId: input.linking.linkingFromTaskId,
      segmentEditTaskId: input.segmentEditTaskId,
      taskIdsOrder: input.occupancyData.taskIdsOrder,
      taskLinks: input.taskLinks,
      taskPositions: input.taskPositions,
      tasksMap: input.occupancyData.tasksMap,
      onDeleteLink: input.occupancyCallbacks.onDeleteLink,
    },
    statusColumnWidth: layout.statusColumnWidth,
    taskColumnWidth: input.scroll.taskColumnWidth,
    onDragEnd: input.handleDragEnd,
  });
}
